### ISSUE TITLE
nice idea

### ISSUE THREAD

**Issue by zartan9** [haroldo-ok/BlocklyVN8bit#10]
trying to make game with it.. but sometimes compiler fails...what can i do to make it work? Also do you add blockly to any other retro game engine (like unity 8bit)...

**Comment by haroldo-ok** [comment]
Hello,

What kind of error is being displayed by the compiler?

As for using Blockly on other retro game engines... yes, it is possibl:; Blockly is designed to be used to generate code for almost any programming language, as long as someone writes a code generator for the target language; I, myself have already used it to make code generators for various retro platforms:
* https://github.com/haroldo-ok/blockly-z80
* https://github.com/haroldo-ok/vcs-game-maker
* https://github.com/haroldo-ok/BlocklyVN8bit
* https://github.com/haroldo-ok/BlocklyVN32X

**Comment by zartan9** [comment]
Hi I'm trying to use blocklyvn8bit it worked once but now just says compilation failed failed to run emulator (c64). How can I export a d64 file from it? Thanks

**Comment by haroldo-ok** [comment]
The d64 file will be in the folder `8bit-Unity/build` but, if it is having a compilation problem, it won't be generated.

When the `compilation failed` message appears, generally, the real cause of the failure will be a few lines before it.

Could you, please, copy the last few lines of the console, so that we can see the error?

**Comment by zartan9** [comment]
hi thanks for reply! i attached an export... here is what is says:
Loading project Gameon1
Loading project...
The project was loaded!
-----------------------
Starting compilation...
Compilation failed!
Failed to run emulator
[Gameon1.vn32x.zip](https://github.com/haroldo-ok/BlocklyVN8bit/files/7577357/Gameon1.vn32x.zip)
!

**Comment by haroldo-ok** [comment]
That's weird; it usually gives a more detailed log whenever something goes wrong or not...
Later, I will take a look at your project to see if I can reproduce the problem.

**Comment by haroldo-ok** [comment]
Yes, there is definitely some bug on the internal function `Blockly.Arduino.scrubLocalVars_`, at the moment it tries to collect variable declarations to move to the top of the function to generate.

**Comment by haroldo-ok** [comment]
Okay, the bug is fixed.
You can download version 0.2.2 from here: 
https://github.com/haroldo-ok/BlocklyVN8bit/releases/download/v0.2.2/BlocklyVN8bit-0.2.2.7z

**Comment by zartan9** [comment]
works great thanks! i pasted info below in case it helps. Also are one of your projects blockly8bit for platformer games? thatd be a fun way to make c64 side scroller!   ill keep checking for updates!
Starting compilation...
The file was saved: test.builder
The file was saved: src/generated_script.c
The chunk file was saved: chunks-atari.txt
The chunk file was saved: chunks-apple.txt
The chunk file was saved: chunks-c64.txt
The chunk file was saved: chunks-oric.txt
The chunk file was saved: chunks-lynx.txt
Compilation done!
-----------------------
Building and starting emulator...

 C:\Users\gabriel\Desktop\blockly\BlocklyVN8bit-0.2.2\8bit-Unity\build>echo off 
A subdirectory or file c64 already exists.
--------------- CONVERT ASSETS --------------- 
Generated build/c64/sylviegi.cnk [60, 96, 40, 104]
 Generated build/c64/sylvieno.cnk [60, 96, 40, 104]
DONE
--------------- COMPILE PROGRAM ---------------
unity\charmap.c(355): Warning: Converting pointer to integer without a cast
 unity\charmap.c(356): Warning: Converting pointer to integer without a cast
 unity\charmap.c(357): Warning: Converting pointer to integer without a cast
 unity\charmap.c(358): Warning: Converting pointer to integer without a cast
 unity\charmap.c(363): Warning: Converting pointer to integer without a cast
 unity\charmap.c(367): Warning: Converting pointer to integer without a cast
 unity\charmap.c(393): Warning: Converting pointer to integer without a cast
 unity\charmap.c(414): Warning: Variable 'i' is defined but never used
unity\chunks.c(172): Warning: Converting pointer to integer without a cast
 unity\chunks.c(243): Warning: Converting pointer to integer without a cast
unity\net-base.c(83): Warning: Control reaches end of non-void function
 unity\net-base.c(83): Warning: Parameter 'ip' is never used
unity\net-url.c(80): Warning: Parameter 'timeOut' is never used
unity\net-tcp.c(52): Warning: Parameter 'slot' is never used
unity\net-udp.c(44): Warning: Converting pointer to integer without a cast
 unity\net-udp.c(55): Warning: Parameter 'slot' is never used
unity\net-web.c(50): Warning: Parameter 'port' is never used
 unity\net-web.c(50): Warning: Parameter 'timeOut' is never used
 unity\net-web.c(70): Warning: Parameter 'buffer' is never used
 unity\net-web.c(70): Warning: Parameter 'length' is never used
 unity\net-web.c(80): Warning: Parameter 'buffer' is never used
 unity\net-web.c(80): Warning: Parameter 'length' is never used
 unity\net-web.c(107): Warning: Parameter 'timeOut' is never used
unity\sprites.c(151): Warning: Parameter 'filename' is never used
 unity\sprites.c(193): Warning: Integer constant is long
 unity\sprites.c(196): Warning: Integer constant is long
 unity\sprites.c(197): Warning: Integer constant is long
 unity\sprites.c(200): Warning: Integer constant is long
 unity\sprites.c(230): Warning: Parameter 'frames' is never used
 unity\sprites.c(230): Warning: Parameter 'cols' is never used
 unity\sprites.c(230): Warning: Parameter 'rows' is never used
 unity\sprites.c(239): Warning: Integer constant is long
 unity\sprites.c(243): Warning: Parameter 'offset' is never used
 unity\sprites.c(554): Warning: Integer constant is long
 unity\sprites.c(556): Warning: Integer constant is long
 unity\sprites.c(557): Warning: Integer constant is long
 unity\sprites.c(557): Warning: Integer constant is long
 unity\sprites.c(559): Warning: Integer constant is long
 unity\sprites.c(560): Warning: Integer constant is long
 unity\sprites.c(560): Warning: Integer constant is long
 unity\sprites.c(584): Warning: Integer constant is long
 unity\sprites.c(584): Warning: Integer constant is long
 unity\sprites.c(620): Warning: Integer constant is long
 unity\sprites.c(620): Warning: Integer constant is long
 unity\sprites.c(647): Warning: Integer constant is long
unity\C64\VIC2.c(41): Warning: Integer constant is long
 unity\C64\VIC2.c(42): Warning: Integer constant is long
 unity\C64\VIC2.c(43): Warning: Integer constant is long
 unity\C64\VIC2.c(58): Warning: Integer constant is long
 unity\C64\VIC2.c(59): Warning: Integer constant is long
 unity\C64\VIC2.c(60): Warning: Integer constant is long
projects/test/src/vn_engine.c(66): Warning: Control reaches end of non-void function
 projects/test/src/vn_engine.c(66): Warning: Variable 'selected' is defined but never used
 projects/test/src/vn_engine.c(140): Warning: Variable 'charW' is defined but never used
 projects/test/src/vn_engine.c(140): Warning: Variable 'spaceW' is defined but never used
 projects/test/src/vn_engine.c(198): Warning: Variable 'mn_option_1' is defined but never used
 projects/test/src/vn_engine.c(198): Warning: Variable 'mn_choice_2' is defined but never used
 projects/test/src/vn_engine.c(198): Warning: Variable 'mn_choice_3' is defined but never used
projects/test/src/generated_script.c(16): Warning: Pointer assignment to 'char *' from 'const char *' discards qualifiers
 projects/test/src/generated_script.c(25): Warning: Pointer assignment to 'char *' from 'const char *' discards qualifiers
 projects/test/src/generated_script.c(26): Warning: Pointer assignment to 'char *' from 'const char *' discards qualifiers
 projects/test/src/generated_script.c(78): Warning: Pointer assignment to 'char *' from 'const char *' discards qualifiers
 projects/test/src/generated_script.c(79): Warning: Pointer assignment to 'char *' from 'const char *' discards qualifiers
Reading "build/c64/test.bin", loading from $1801 to $526B.
 Crunching from $1801 to $526B.
 Phase 1: Instrumenting file
 -----------------------------
 Length of indata: 14954 bytes.

 Instrumenting file, done.
 
 Phase 2: Calculating encoding
 -----------------------------
 pass 1: optimizing ..
size 66497.0 bits ~8313 bytes
 pass 2: optimizing ..

 size 66414.0 bits ~8302 bytes
 pass 3: optimizing ..

 size 66404.0 bits ~8301 bytes
 pass 4: optimizing ..
Calculating encoding, done.
 
 Phase 3: Generating output file
 ------------------------------
 Enc: 1011223332302300,2122,2132232455667888,3332445667889AAD
Length of crunched data: 8329 bytes.
 Crunched data reduced 6625 bytes (44.30%)
 Literal sequences are used, length 1 sequences are used,
 length 123 mirrors are not used, max length used is 125 and
 the safety offset is 3.
 Target is self-decrunching C64 executable,
 jmp address $180D.
 Writing "build/c64/loader.prg" as prg, saving from $0801 to $2996.
 Memory layout: |Start |End |
 Crunched data | $081C| $28A4|
 Decrunched data | $1801| $526B|
 Decrunch table | $0334| $03D0|
 Decruncher | $00FD| $01A6| and $9F,$A7,$9E,$AE,$AF
 Decrunch effect writes to $DBE7.
 Decruncher: |Enter |During|Exit |
 RAM config | $37| $37| $37|
 IRQ enabled | 1| 1| 1|
 DONE
 --------------- C64 DISK BUILDER --------------- 
Unit: 0 Formatting in unit 8... Writing file `BUILD/C64/LOADER.PRG' as `LOADER.PRG' to unit 8. Writing file `BUILD/C64/CLUB.IMG' as `CLUB.IMG' to unit 8. Writing file `BUILD/C64/LECTUREH.IMG' as `LECTUREH.IMG' to unit 8. Writing file `BUILD/C64/SYLVIEGI.CNK' as `SYLVIEGI.CNK' to unit 8. Writing file `BUILD/C64/SYLVIENO.CNK' as `SYLVIENO.CNK' to unit 8.
DONE
 Press any key to continue .

**Comment by haroldo-ok** [comment]
Thanks for the suggestion! 👍

Every now and then, I try to create some new game-making tool; for example:
* A few months ago, I tried my hand at creating Blockly-based a game making tool for Atari 2600: https://github.com/haroldo-ok/vcs-game-maker
* I am currently making a shoot-em-up for the Sega Master System, that I intend to eventually turn into a generic shoot-em-up engine, in the long term: https://github.com/haroldo-ok/dragon-blaster (in fact, I already made another short game based on this partially implemented engine: https://github.com/haroldo-ok/binary-gunner)

**Comment by zartan9** [comment]
Great! I'llook into it. On itch.io there is an "Atari VCS maker" that also uses blockly maybe collab. I'll keep looking for your engines thanks

**Comment by haroldo-ok** [comment]
I'm glad to have helped. Have fun!

**Comment by zartan9** [comment]
ps. would be wild to link to NFT in atari/c64!! Im looking into moralis.io but its kinda over my head!!  be well
