### ISSUE TITLE
blocklyvn8bit character name

### ISSUE THREAD

**Issue by zartan9** [haroldo-ok/BlocklyVN8bit#22]
hi, im able to make the block for character (with a name) but not able to show it
it just says "character name" over the text.. also based on 8bit im not able to see this output to nes though.. keep on gaming!

**Comment by zartan9** [comment]
hi here is how it looks now... Im also doing something else wrong because the other choices 3 and 5 dont seem to work when i press the numbers 3 / 5...

![choices](https://user-images.githubusercontent.com/74879950/159817921-87878a04-e4c7-4d8d-a762-9450696a5b87.png)

**Comment by haroldo-ok** [comment]
Since "choices" is a numeric variable, it can only have a single value, so, if you set it to 3, then set it to 5, it will always keep the last value you set, so, in the example above:

```
set choices to 3
set choices to 5
if choices = 3:
    say "go on"
if choices = 5:
    say "go on2"
```
In the example above, it will always say "go on2", because it will set "choices" to 3, then, without doing anything else, it will set "choices" do 5, and only then it will execute the two "ifs "; since "choices" will be 5 by the time the "ifs" are reached, only the expression from the second if will be evaluated as true.

**Comment by zartan9** [comment]
so if i want 3 or 4 options do i set them to if else/ else/ else?
i still see "character name"

**Comment by haroldo-ok** [comment]
Every menu option must be added inside the "menu" block. If you want to have 3 or 4 options, they will have to be added inside the "menu" block; you can combine them with if/else, if you want, but this if/else also has to be inside the menu block.

You have to set the character name _before_ calling the menu, or else, it will use the last character name that was used, wich means that if you didn't call the "character" block even once before opening the menu, it will use the default value, which is, literally, "character name"

**Comment by zartan9** [comment]
hi ok so im confusing myself! whats great about your software is the visual blocks which help me learn, can you post a screen shot of how a working example looks (so player can have like 3 choices within a menu) thank you..

**Comment by haroldo-ok** [comment]
Okay, I will try to make an example later.

**Comment by haroldo-ok** [comment]
Okay, here's an example with 5 menu options.

![image](https://user-images.githubusercontent.com/1457465/160197870-1566fcf2-a594-4f4d-b69d-720a3327a58d.png)

**Comment by zartan9** [comment]
On Friday, March 25, 2022, 04:41:02 PM EDT, Haroldo de Oliveira Pinheiro ***@***.***> wrote:  
 
 


Okay, here's an example with 5 menu options.



—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

.thanks I'll take a lookMessage ID: ***@***.***>

**Comment by zartan9** [comment]
hi thank you it's working! still not sure where to define character name (have another graphic screenshot) but i have a start now.. i mayve mentioned this but a suggestion is not have the options black box take up the whole width.
PS any plans for NES (as unity 8bit does that) anyway i like your software I will keep exploring :)
![hm3](https://user-images.githubusercontent.com/74879950/160266918-96666a78-8b00-4399-b156-2b7df37121d4.png)

**Comment by haroldo-ok** [comment]
Hello,

In order to set the character name, you have to add the "Character" block *before* the menu.

As for NES,  good call, I didn't notice they had added support for that platform 
https://github.com/haroldo-ok/BlocklyVN8bit/issues/23

**Comment by zartan9** [comment]
![hm4](https://user-images.githubusercontent.com/74879950/160295233-e1bec32f-f306-430c-9e89-05d3851542db.png)
hi thanks yes NES would be fun addition. OK, please correct me i have character named "information" before menu, but doesnt show up (yet).. thanks...

**Comment by haroldo-ok** [comment]
Interesting... there really seems to be a bug with the character name block; it should be updating the name, but isn't...

**Comment by zartan9** [comment]
got it. keep up the nice work! Ill keep exploring the engine :)

**Comment by zartan9** [comment]
hi is there a limit of images(in the editor?) I can seem to scroll to get to the other photos in the bg folder from editr)
thanks
![choices2](https://user-images.githubusercontent.com/74879950/164817786-172fcb4b-a353-4132-8e18-0ce7af52d938.png)

**Comment by haroldo-ok** [comment]
Hello, again;
No,there is no limit of images in the editor, but there does seem to be a bug where the image selection pop-up isn't correctly handling the large amount of options...

**Comment by zartan9** [comment]
yes sir! I keep lookin fwd to updates as your engine is easy to use :) thanks!

**Comment by haroldo-ok** [comment]
Hello, again, I fixed the bug with the image list:

![image](https://user-images.githubusercontent.com/1457465/171061467-60740961-a6c7-410e-acba-979bff1dee54.png)

You can get the new version from here:
https://github.com/haroldo-ok/BlocklyVN8bit/releases/download/v0.2.3/BlocklyVN8bit-0.2.3.7z

**Comment by zartan9** [comment]
thanks will take a look

-----Original Message-----

**Comment by haroldo-ok** [comment]
Okay, the character name bug has been fixed, too:
https://github.com/haroldo-ok/BlocklyVN8bit/releases/tag/v0.2.5

**Comment by zartan9** [comment]
great hope to test in near future :) keep up nice work!


-----Original Message-----

**Comment by zartan9** [comment]
Ok at least I'm setting it up correctly😁
    On Sunday, March 27, 2022, 03:14:53 PM EDT, Haroldo de Oliveira Pinheiro ***@***.***> wrote:  
 
 


Interesting... there really seems to be a bug with the character name block; it should be updating the name, but isn't...
