### ISSUE TITLE
Problem when selecting between a large amount of images

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/BlocklyVN8bit#24]
The selection popup isn't working correctly when there are too many images to list

> hi is there a limit of images(in the editor?) I can seem to scroll to get to the other photos in the bg folder from editr)
> thanks
> ![choices2](https://user-images.githubusercontent.com/74879950/164817786-172fcb4b-a353-4132-8e18-0ce7af52d938.png)

> _Originally posted by @zartan9 in https://github.com/haroldo-ok/BlocklyVN8bit/issues/22#issuecomment-1107048176_

**Comment by haroldo-ok** [comment]
Part of the problem seems to be caused by the fact that the tool is using a really old version of Blockly; it seems that the dropdown height problem has been fixed somewhere around 2019.

References:
- https://github.com/google/blockly/issues/1364
- https://github.com/google/blockly/issues/2337

**Comment by zartan9** [comment]
thanks, its been a while, I downloaded new version but "Failed to run emulator!" how do i connect it again? Im tryn to run as c64

**Comment by haroldo-ok** [comment]
That's weird... it seems to be loading the project from the right place, but executing the emulator from the wrong place. I will have to take a look at this later.

**Comment by haroldo-ok** [comment]
Okay, I realeased a new version; it should fix the compilation bug.

Version 0.2.4: https://github.com/haroldo-ok/BlocklyVN8bit/releases/download/v0.2.4/BlocklyVN8bit-0.2.4.7z

**Comment by zartan9** [comment]
hi yes i can see a scrolling list of pictures now thank you! I duplicated pics and renamed them hi, so its hi(2).jpg hi(3).jpgthen i exported and got error are () not allowed in name? it was working before i duplicated the pictures (for c64, the atari and lynx didnt even beforehand). Cant wait to see NES in the list! 


-----Original Message-----

**Comment by haroldo-ok** [comment]
In theory, the tool shouldn't have such a limitation, but since it wasn't tested on this specific situation, there's always the possibility of an unforesseen bug. That definitely warrants further investigation.
