### ISSUE TITLE
Fix handling of non-alphanumeric characters on image file names.

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/BlocklyVN8bit#28]
Using symbolic characters on an image's file name causes bugs when generating the code.

-----Original Message-----

hi yes i can see a scrolling list of pictures now thank you! I duplicated pics and renamed them hi, so its hi(2).jpg hi(3).jpgthen i exported and got error are () not allowed in name? it was working before i duplicated the pictures (for c64, the atari and lynx didnt even beforehand). Cant wait to see NES in the list! 

-----Original Message-----
From: Haroldo de Oliveira Pinheiro ***@***.***>
To: haroldo-ok/BlocklyVN8bit ***@***.***>
Cc: zartan9 ***@***.***>; Mention ***@***.***>
Sent: Wed, Jun 1, 2022 6:59 pm
Subject: Re: [haroldo-ok/BlocklyVN8bit] Problem when selecting between a large amount of images (Issue #24)

Okay, I realeased a new version; it should fix the compilation bug.Version 0.2.4: https://github.com/haroldo-ok/BlocklyVN8bit/releases/download/v0.2.4/BlocklyVN8bit-0.2.4.7z—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

_Originally posted by @zartan9 in https://github.com/haroldo-ok/BlocklyVN8bit/issues/24#issuecomment-1145366562_

**Comment by zartan9** [comment]
hi i went back to reinstall blocklyvn8bit but i cant find that version/ says not found. where is the latest version i can install? I have a version but it doesnt open in win 10. thnks!

**Comment by haroldo-ok** [comment]
Hello; the versions would be on the "Releases" page: https://github.com/haroldo-ok/BlocklyVN8bit/releases

**Comment by zartan9** [comment]
Awesome ! Thanks! If i start making the game with current engine, would it work with new version (that includes NES support?)
be well :)

**Comment by haroldo-ok** [comment]
> Awesome ! Thanks!

You're very welcome. 😀

>  If i start making the game with current engine, would it work with new version (that includes NES support?) . 

Unfortunately, not quite:

- The current version of BlocklVN8bit won't list the NES among the compilation targets;
- Also, since it does not know about the NES support, it won't convert the images to the correct resolution/palette;
- Plus, unless it is modified to do it, it won't know it needs to read from the NES joypad;
- The generated C code should be mostly correct for the NES, but due to the aforementioned problems, it won't quite work as intended.

> Also if possible to get back to a mAIN menu at any time is there a way to set that up with a key press? Like option "mainmenu" if ...? be well :)

It should be possible; I recorded it for later implementation on #32

**Comment by zartan9** [comment]
got it! Thats ok i like c64 more than nes!! 
![tes](https://user-images.githubusercontent.com/74879950/189550805-f23131e6-3829-4f23-a501-3be3b93a7ddc.jpg)
Ill use it for mostly c64 .. i have like 30 pictures in one label, but it gets stuck on the one in photo (I have original on right).
it seems like its trnsparent also where the moon/sun is so I'm hoping this can be fixed somehow? Thank you :)

**Comment by haroldo-ok** [comment]
It seems to be using some non-C64 colors, which may be confusing 8bit-Unity's image converter.
For this one, I would recommend asking on the 8bit-Unity's forums: https://8bit-unity.com/?post_type=forum

**Comment by zartan9** [comment]
hi i changed colors/used another picture ... the other picture works if its the first picture, but when it gets to 18th picture it freezes on that picture/gets corrupt.. any idea for that? I can send files if need be...

**Comment by haroldo-ok** [comment]
Hello; 

That's weird; I wonder if there's a memory leakage or a memory overflow somewhere? If you show the 18th picture before the others, does the error occur right away, or does it happen with the 18th picture regardless of order?

Attaching the project could help checking what's going wrong.

**Comment by zartan9** [comment]
[projects - Copy.zip](https://github.com/haroldo-ok/BlocklyVN8bit/files/9559356/projects.-.Copy.zip)
hi i tried picture reordering, it always happens around 18th picture (the text changes but the pictures stay stuck!) Ive included
example hit 1, then 1 then keep hitting 1 :) Also I tried to see if its the same in other platforms but I only could get atari opening (probably since I dont have the other emulators set up right yet) but I got a weird screen : 
![tes2](https://user-images.githubusercontent.com/74879950/189967865-1bc9816a-6e42-4142-a88c-344003158dbc.jpg)
not related? Hope you can see where the issue is Im making progress otherwise!!!

**Comment by haroldo-ok** [comment]
Hello;
> hi i tried picture reordering, it always happens around 18th picture (the text changes but the pictures stay stuck!) Ive included
example hit 1, then 1 then keep hitting 1 :)

Thanks for the clarification; I shall take a look at the issue later on.

> I tried to see if its the same in other platforms but I only could get atari opening (probably since I dont have the other emulators set up right yet) but I got a weird screen :

Weird; maybe it failed to load the program?

**Comment by zartan9** [comment]
yes please keep me posted i did another section by chosing #2 and it does the same thing with the 
other set of pics (around 18!)

**Comment by zartan9** [comment]
yes that you that works! I took out all the symbols and it can scroll in c64 thank you.


-----Original Message-----
From: Haroldo de Oliveira Pinheiro ***@***.***>
To: haroldo-ok/BlocklyVN8bit ***@***.***>
Cc: zartan9 ***@***.***>; Mention ***@***.***>
Sent: Fri, Jun 3, 2022 6:59 am
Subject: [haroldo-ok/BlocklyVN8bit] Fix handling of non-alphanumeric characters on image file names. (Issue #28)

Using symbolic characters on an image's file name causes bugs when generating the code.-----Original Message-----hi yes i can see a scrolling list of pictures now thank you! I duplicated pics and renamed them hi, so its hi(2).jpg hi(3).jpgthen i exported and got error are () not allowed in name? it was working before i duplicated the pictures (for c64, the atari and lynx didnt even beforehand). Cant wait to see NES in the list! -----Original Message-----

**Comment by haroldo-ok** [comment]
Update: it seems to be an error on the naming of the variable:
```c
#include "script.h"

const char *vi_club (1) = "club1.img";


void *vn_start()
{


  vnScene(vi_club (1));
  vnText("Test");


  return vn_start;
}
```

The file itself was already being renamed correctly; it is the name of the variable that is being generated incorrectly; correction in progress.

**Comment by haroldo-ok** [comment]
Fixed on version https://github.com/haroldo-ok/BlocklyVN8bit/releases/tag/v0.2.7
